# Generated by Django 5.1.1 on 2024-10-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0004_alter_apartment_options_alter_house_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_tariff', models.DecimalField(decimal_places=2, help_text='Тариф за воду', max_digits=10)),
                ('common_property_maintenance_tariff', models.DecimalField(decimal_places=2, help_text='Тариф за содержание общего имущества', max_digits=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_calculations', to='housing.apartment')),
            ],
        ),
    ]
