# Generated by Django 5.1.1 on 2024-10-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0002_alter_apartment_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reading', models.IntegerField(default=0, help_text='Текущее показание счетчика')),
                ('previous_reading', models.IntegerField(default=0, help_text='Предыдущее показание счетчика')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to='housing.apartment')),
            ],
            options={
                'verbose_name': 'water_meter',
                'verbose_name_plural': 'water_meters',
            },
        ),
    ]
