# Generated by Django 5.1.1 on 2024-10-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_apartment_options_alter_house_options'),
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watermeter',
            options={'verbose_name': 'Счетчик воды', 'verbose_name_plural': 'Счетчики воды'},
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_water_meters', to='housing.apartment'),
        ),
    ]
