# Generated by Django 5.1.1 on 2024-10-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('building', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('area', models.FloatField(help_text='Площадь квартиры в квадратных метрах')),
                ('owner', models.CharField(max_length=255)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='housing.house')),
            ],
        ),
    ]
