# Generated by Django 5.1.1 on 2024-10-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_apartment_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('street', 'building')},
        ),
    ]
