# Generated by Django 5.1.1 on 2024-10-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_alter_house_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
