# Generated by Django 5.1.1 on 2024-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_apartment_options_alter_house_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
